name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - master  # Triggar workflow varje gång du pushar till main-branchen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checka ut koden från repo
      - name: Check out the repository
        uses: actions/checkout@v2

      # Logga in på Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bygg Docker-imagen
      - name: Build Docker image
        run: docker build -t maxguclu/demo:latest .

      # Tagga Docker-imagen
      - name: Tag Docker image
        run: docker tag maxguclu/demo:latest maxguclu/demo:latest

      # Pusha Docker-imagen till Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push maxguclu/demo:latest
